name: findway_mobile
description: Global humanitarian search platform.
publish_to: 'none'

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  image_picker: ^1.1.2  # Эта версия еще не требует AGP 8.9.1
  
  # Icons (Исправлен отступ)
  bootstrap_icons: ^1.10.0
  
  # ТИПОГРАФИКА (Для того самого Orbitron без ручной возни с файлами)
  google_fonts: ^6.1.0 
  
  # ВИЗУАЛЬНЫЕ ЭФФЕКТЫ
  # Для "стеклянных" карточек и размытия (Glassmorphism)
  glass: ^1.0.0
  # Для неонового мерцания и плавных появлений
  flutter_animate: ^4.5.0
  # Красивые лоадеры вместо стандартных кружков
  flutter_spinkit: ^5.2.0
  # Скелетоны для загрузки (Production-first UX)
  skeletonizer: ^1.2.0

  # State Management & DI
  flutter_bloc: ^8.1.0
  get_it: ^7.6.0
  
  dio_cookie_manager: ^3.0.0
  cookie_jar: ^4.0.8
  # Network & Data
  dio: ^5.4.0
  path_provider: ^2.1.1  # Оставь только это вхождение
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18
  dartz: ^0.10.1
  equatable: ^2.0.8
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.14.0
  build_runner: ^2.4.8 # Обновил до стабильного

flutter:
  # Этот флаг разрешает использование встроенных иконок Material
  uses-material-design: true

  # Регистрация ресурсов. Ключ 'assets' пишется ТОЛЬКО ОДИН РАЗ.
  assets:
    - assets/images/  # Этого достаточно, чтобы увидеть ВСЕ файлы в этой папке
    - assets/images/peop.png
    - assets/images/cat.png
    - assets/images/things.png